### ISSUE TITLE
Control two stepper motors

### ISSUE THREAD

**Issue by Nico4589** [bblanchon/ArduinoContinuousStepper#10]
Hi, is it possible to control two stepper motors at the same time that go at two different speeds? If so, how can I do it?

**Comment by Nico4589** [comment]
> Hi, is it possible to control two stepper motors at the same time that go at two different speeds? If so, how can I do it?

**Comment by bblanchon** [comment]
Hi @Nico4589,

Yes, it's possible by creating two instances of `ContinuousStepper`.
Of course, you need to call `.loop()` for each one.

Best regards,
Benoit

**Comment by bblanchon** [comment]
Duplicate of #8
