### ISSUE TITLE
problem with stop()

### ISSUE THREAD

**Issue by ltspicer** [bblanchon/ArduinoContinuousStepper#13]
I have a problem with stop() .
When **stepper.stop();** is executed, the motor **stops abruptly** and starts decelerating when the next **stepper.loop();** is processed.

```
...
...
void loop() {
  if (Serial.available() > 0) {
    int rlen = Serial.readBytesUntil('\n', buffer, BUFFER_SIZE);
    String buf = buffer;
    if (rlen > 0) {
      if (buf.substring(0,rlen) == "stop") {
        stepper.stop();
        Serial.println("stop");
      } else if (buf.substring(0,rlen) == "start") {
        stepper.spin(500);
        Serial.println("start");
      }
    }
  }
  stepper.loop();
}
```

**Comment by bblanchon** [comment]
Hi @ltspicer,

`stop()` does nothing more than set the target speed to 0.

An abrupt stop is likely caused by `loop()` not being called.
For example, this could happen if `Serial.readBytesUntil()` timeouts.

Best regards,
Benoit

**Comment by ltspicer** [comment]
That was exactly the problem.
Thank you very much.
This is a fantastic library. Exactly what I need.

**Comment by bblanchon** [comment]
You're welcome, @ltspicer.
Thanks for the kind words :heart:
Don't forget to star the project on GitHub ;-)

**Comment by ltspicer** [comment]
Of course.
There will be a special "CNC" machine that heads beer cans live behind the counter.
These can then be used like a drinking cup.
There will be 1-2 stepper motors and a 30N cylinder.
But right now it's the prototype early stage.
