### ISSUE TITLE
Acceleration is bit abrupt

### ISSUE THREAD

**Issue by aghabilal97** [bblanchon/ArduinoContinuousStepper#16]
I am having issue with the abrupt change with the acceleration of the motor that is the frequency of the wave changes directly from 10 kHz to directly 30 or 40 kHz Can you please help me in that regard

**Comment by bblanchon** [comment]
Could this be the same issue as https://github.com/bblanchon/ArduinoContinuousStepper/issues/15#issuecomment-1914354359?

**Comment by aghabilal97** [comment]
No I meant the frequency of the signal input that we are giving to the motor does not change in a regular manner instead it increases smoothly from 1kHz to 10 kHz and after a lag directly shifts to 30 or 40kHz

**Comment by aghabilal97** [comment]
Yes thank you
