### ISSUE TITLE
Add isPowerOn

### ISSUE THREAD

**Issue by Nersgatt** [bblanchon/ArduinoContinuousStepper#17]
Hello!

For some reason i need the information, if the Power is on or off. For this, i added 

  bool isPowerOn() const {
    return status_ != OFF;
  }

in ContinousStepperImpl.hpp. Maybe consider to adopt this to the next version of your library.

Best regards!

**Comment by bblanchon** [comment]
Hi @Nersgatt,

Thank you for this suggestion.

I added `isPowered()` in version 3.1.0.

Best regards,
Benoit
