### ISSUE TITLE
Enable Pin

### ISSUE THREAD

**Issue by andreasr81** [bblanchon/ArduinoContinuousStepper#18]
Hi, were do I put the enable pin?

setEnablePin(14); ?!

thanks

**Comment by bblanchon** [comment]
Hi @andreasr81,

`stepper.setEnablePin(14)` should work.
What did you try?

Best regards,
Benoit

**Comment by andreasr81** [comment]
oh thanks, Iam a noob, and how can I change the directions?
How can I drive 2 stepper in my code?  Thanks for the help

**Comment by bblanchon** [comment]
You can change the direction by using a negative speed.
You can drive two motors with two instances of `ContinuousStepper<T>`.

**Comment by andreasr81** [comment]
hey, thanks a lot!

regards

**Comment by bblanchon** [comment]
Your welcome @andreasr81.
Thank you for using this library!
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoContinuousStepper/stargazers) to support the project 😉
