### ISSUE TITLE
Do number of steps

### ISSUE THREAD

**Issue by spencerandhill** [bblanchon/ArduinoContinuousStepper#4]
Hi!
Is there any way to do a defined number of steps with your library?

Something like "step(30, 200)" for example. That would do 30 steps with a speed of 200.

I'm searching for a non-blocking library to do defined number of steps in continuous mode. Neither accelstepper or your library does that, right?

Best

**Comment by bblanchon** [comment]
Hi,

The best tool for this job is AccelStepper.
Simply call [`setMaxSpeed()`](https://www.airspayce.com/mikem/arduino/AccelStepper/classAccelStepper.html#abee8d466229b87accba33d6ec929c18f) and  [`move()`](https://www.airspayce.com/mikem/arduino/AccelStepper/classAccelStepper.html#a68942c66e78fb7f7b5f0cdade6eb7f06).

Best regards,
Benoit
