### ISSUE TITLE
Controlling stepper driver boards with multiple stepping options

### ISSUE THREAD

**Issue by rikaad** [bblanchon/ArduinoContinuousStepper#5]
HI,
On stepper driver boards with multiple stepping options (1/8th stepping, 1/16 stepping .....) and multiple pins to set those options, e.g the big easy stepper driver board, do the stepping option pins need to be set specifically by the controller (e.g. an Arduino) or is this completely handled internally by the continuous stepper library.

Regards,

Richard.

**Comment by bblanchon** [comment]
Hi Richard,

As far as I know, libraries don't deal with the controller's settings.
You just need to adapt the speed in your application.

Best regards,
Benoit
